# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sunny
tagline:          'A iOS tech blog'
description:      'This is my personal blog Welcome ÔºÅ<a href="https://twitter.com/sipdar" target="_blank">@sunny</a>.'
url:              https://github.com/sipdar
baseurl:          /

author:
  name:           'Sunny'
  url:            https://twitter.com/sipdar

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sipdar
